apiVersion: apps/v1
kind: Deployment
metadata:
  name: swe645-hw2-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-swe645-hw2-deployment
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-default-swe645-hw2-deployment
    spec:
      containers:
        - name: container-0
          image: mgurung3/hw1-website:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: hw2-service
              protocol: TCP
