apiVersion: apps/v1
kind: Deployment
metadata:
  name: swe645-hw2-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swe645-hw2
  template:
    metadata:
      labels:
        app: swe645-hw2
    spec:
      containers:
        - name: hw1-website
          image: mgurung3/hw1-website:latest
          ports:
            - containerPort: 80
